/* External assets extracted from the original single-file version. */
const U = {
  "p1": "images/p1.jpg",
  "p2": "images/p2.jpg",
  "p3": "images/p3.jpg",
  "p4": "images/p4.jpg",
  "p5": "images/p5.jpg",
  "p6": "images/p6.jpg",
  "p7": "images/p7.jpg",
  "p8": "images/p8.jpg",
  "p9": "images/p9.jpg",
  "p10": "images/p10.jpg",
  "p11": "images/p11.jpg",
  "p12": "images/p12.jpg",
  "p13": "images/p13.jpg",
  "p14": "images/p14.jpg",
  "p15": "images/p15.jpg",
  "p16": "images/p16.jpg",
  "p17": "images/p17.jpg",
  "corolla-1": "images/corolla-1.jpg",
  "corolla-2": "images/corolla-2.jpg",
  "corolla-3": "images/corolla-3.jpg",
  "new-gym-1": "images/new-gym-1.jpg",
  "new-gym-2": "images/new-gym-2.jpg",
  "new-cat": "images/new-cat.jpg",
  "new-portrait": "images/new-portrait.jpg",
  "new-snow-1": "images/new-snow-1.jpg",
  "new-snow-2": "images/new-snow-2.jpg",
  "new-snow-3": "images/new-snow-3.jpg",
  "new-snow-4": "images/new-snow-4.jpg",
  "new-snow-5": "images/new-snow-5.jpg",
  "car-dusk": "images/car-dusk.jpg",
  "cafe": "images/cafe.jpg",
  "food-4": "images/food-4.jpg",
  "ride-5": "images/ride-5.jpg",
  "boxing": "images/boxing.jpg",
  "ride-4": "images/ride-4.jpg",
  "snow-core": "images/snow-core.jpg",
  "food-7": "images/food-7.jpg",
  "cat-1": "images/cat-1.jpg",
  "snow-falling": "images/snow-falling.jpg",
  "food-3": "images/food-3.jpg",
  "snow-close": "images/snow-close.jpg",
  "food-5": "images/food-5.jpg",
  "snow-tree": "images/snow-tree.jpg",
  "selfie-car": "images/selfie-car.jpg",
  "journey-2": "images/journey-2.jpg",
  "ride-3": "images/ride-3.jpg",
  "ferry-bench": "images/ferry-bench.jpg",
  "food-8": "images/food-8.jpg",
  "ride-2": "images/ride-2.jpg",
  "food-6": "images/food-6.jpg",
  "food-2": "images/food-2.jpg",
  "snow-pose": "images/snow-pose.jpg",
  "gym": "images/gym.jpg",
  "fishing-pier": "images/fishing-pier.jpg",
  "drive-night": "images/drive-night.jpg",
  "food-1": "images/food-1.jpg",
  "fishing-rocks": "images/fishing-rocks.jpg",
  "journey-3": "images/journey-3.jpg",
  "journey-1": "images/journey-1.jpg",
  "sydney-bridge": "images/sydney-bridge.jpg",
  "ride-1": "images/ride-1.jpg",
  "ferry-stand": "images/ferry-stand.jpg",
  "cat-2": "images/cat-2.jpg",
  "about": "images/about.jpg",
  "poster-song-1": "images/poster-song-1.jpg",
  "poster-song-2": "images/poster-song-2.jpg"
};
const A = {
  "about": "images/about.jpg",
  "boxing": "images/boxing.jpg",
  "cafe": "images/cafe.jpg",
  "car-dusk": "images/car-dusk.jpg",
  "drive-night": "images/drive-night.jpg",
  "ferry-bench": "images/ferry-bench.jpg",
  "ferry-stand": "images/ferry-stand.jpg",
  "fishing-pier": "images/fishing-pier.jpg",
  "fishing-rocks": "images/fishing-rocks.jpg",
  "food-1": "images/food-1.jpg",
  "food-2": "images/food-2.jpg",
  "food-3": "images/food-3.jpg",
  "food-4": "images/food-4.jpg",
  "food-5": "images/food-5.jpg",
  "food-6": "images/food-6.jpg",
  "food-7": "images/food-7.jpg",
  "food-8": "images/food-8.jpg",
  "gym": "images/gym.jpg",
  "journey-1": "images/journey-1.jpg",
  "journey-2": "images/journey-2.jpg",
  "journey-3": "images/journey-3.jpg",
  "ride-1": "images/ride-1.jpg",
  "ride-2": "images/ride-2.jpg",
  "ride-3": "images/ride-3.jpg",
  "ride-4": "images/ride-4.jpg",
  "ride-5": "images/ride-5.jpg",
  "selfie-car": "images/selfie-car.jpg",
  "snow-close": "images/snow-close.jpg",
  "snow-core": "images/snow-core.jpg",
  "snow-falling": "images/snow-falling.jpg",
  "snow-pose": "images/snow-pose.jpg",
  "snow-tree": "images/snow-tree.jpg",
  "sydney-bridge": "images/sydney-bridge.jpg",
};
const V = {
  "song-1": "videos/song-1.mp4",
  "song-2": "videos/song-2.mp4"
};

document.querySelectorAll('img[data-u]').forEach(i => {
  if (U[i.dataset.u]) i.src = U[i.dataset.u];
});

document.querySelectorAll('img[data-a]').forEach(i => {
  if (A[i.dataset.a]) i.src = A[i.dataset.a];
});

document.querySelectorAll('video[data-v]').forEach(v => {
  if (V[v.dataset.v]) v.src = V[v.dataset.v];
});
